/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRONTEND;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author PC
 */
public class frmTablero extends javax.swing.JFrame {

    /**
     * Creates new form frmTablero
     */
    public frmTablero() {
        initComponents();
        
        jpLong p1 = new jpLong();
        showPanel(p1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLong = new javax.swing.JPanel();
        btnPanelLong = new javax.swing.JButton();
        btnPanelTemp = new javax.swing.JButton();
        jpCont = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        jpLong.setBackground(new java.awt.Color(255, 255, 255));

        btnPanelLong.setText("<- Conversor de longitud");
        btnPanelLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelLongActionPerformed(evt);
            }
        });

        btnPanelTemp.setText("Conversor de temperatura ->");
        btnPanelTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelTempActionPerformed(evt);
            }
        });

        jpCont.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpContLayout = new javax.swing.GroupLayout(jpCont);
        jpCont.setLayout(jpContLayout);
        jpContLayout.setHorizontalGroup(
            jpContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpContLayout.setVerticalGroup(
            jpContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpLongLayout = new javax.swing.GroupLayout(jpLong);
        jpLong.setLayout(jpLongLayout);
        jpLongLayout.setHorizontalGroup(
            jpLongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPanelLong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(btnPanelTemp)
                .addContainerGap())
            .addComponent(jpCont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpLongLayout.setVerticalGroup(
            jpLongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPanelLong, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(btnPanelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpCont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(622, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jpLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPanelLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelLongActionPerformed
        // TODO add your handling code here:
        
        jpLong p1 = new jpLong();
        showPanel(p1);
        
    }//GEN-LAST:event_btnPanelLongActionPerformed

    private void btnPanelTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelTempActionPerformed
        // TODO add your handling code here:

        jpTemp p2 = new jpTemp();
        showPanel(p2);

    }//GEN-LAST:event_btnPanelTempActionPerformed

    private void showPanel(JPanel p){
  
        p.setSize(590, 416);
        p.setLocation(0, 0);
        
        jpCont.removeAll();
        jpCont.add(p, BorderLayout.CENTER);
        jpCont.revalidate();
        jpCont.repaint();
    
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPanelLong;
    private javax.swing.JButton btnPanelTemp;
    private javax.swing.JPanel jpCont;
    private javax.swing.JPanel jpLong;
    // End of variables declaration//GEN-END:variables
}
