/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FRONTEND;

import BACKEND.clsCalculoTemp;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class jpTemp extends javax.swing.JPanel {

    /**
     * Creates new form jpTemp
     */
    public jpTemp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        ctTemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnConverTemp = new javax.swing.JButton();
        ctRespTemp = new javax.swing.JTextField();
        chbCEL1 = new javax.swing.JCheckBox();
        chbFAH1 = new javax.swing.JCheckBox();
        chbKEL1 = new javax.swing.JCheckBox();
        chbCEL2 = new javax.swing.JCheckBox();
        chbFAH2 = new javax.swing.JCheckBox();
        chbKEL2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(608, 416));

        jLabel1.setText("Escoja la unidad de medida que tiene:");

        ctTemp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ctTempKeyTyped(evt);
            }
        });

        jLabel2.setText("Escoja la unidad de medida a la que desea convertir:");

        btnConverTemp.setText("Convertir");
        btnConverTemp.setEnabled(false);
        btnConverTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConverTempActionPerformed(evt);
            }
        });

        ctRespTemp.setEnabled(false);

        buttonGroup1.add(chbCEL1);
        chbCEL1.setText("Celsius");

        buttonGroup1.add(chbFAH1);
        chbFAH1.setText("Fahrenheit");
        chbFAH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFAH1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(chbKEL1);
        chbKEL1.setText("Kelvin");

        buttonGroup2.add(chbCEL2);
        chbCEL2.setText("Celsius");

        buttonGroup2.add(chbFAH2);
        chbFAH2.setText("Fahrenheit");
        chbFAH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFAH2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(chbKEL2);
        chbKEL2.setText("Kelvin");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ctTemp))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(chbCEL2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chbFAH2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chbKEL2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnConverTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ctRespTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 192, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbCEL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbFAH1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chbKEL1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbCEL1)
                    .addComponent(chbFAH1)
                    .addComponent(chbKEL1))
                .addGap(13, 13, 13)
                .addComponent(ctTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbCEL2)
                    .addComponent(chbFAH2)
                    .addComponent(chbKEL2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConverTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctRespTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConverTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConverTempActionPerformed
        // TODO add your handling code here:
        String cajaTemp = ctTemp.getText();
        
        if (chbCEL1.isSelected()){
            if (chbCEL2.isSelected()){
                JOptionPane.showMessageDialog(null, "Porfavor elija una unidad de medida distinta.");
            } else if (chbFAH2.isSelected()){
                double valorTemp = 0;
                double resp = 0;

                valorTemp = Double.parseDouble(   cajaTemp    );

                /*INTANCIO LA CLASE*/
                clsCalculoTemp objCalculoTemp = new clsCalculoTemp();

                resp = objCalculoTemp.fncCelsiusAfahrenheit(valorTemp);

                JOptionPane.showMessageDialog(null, resp);
                ctRespTemp.setText(    String.valueOf(resp)    );
            } else if (chbKEL2.isSelected()){
                double valorTemp = 0;
                double resp = 0;

                valorTemp = Double.parseDouble(   cajaTemp    );

                /*INTANCIO LA CLASE*/
                clsCalculoTemp objCalculoTemp = new clsCalculoTemp();

                resp = objCalculoTemp.fncCelsiusAkelvin(valorTemp);

                JOptionPane.showMessageDialog(null, resp);
                ctRespTemp.setText(    String.valueOf(resp)    );
            }
        } else if (chbFAH1.isSelected()){
            if (chbFAH2.isSelected()){
                JOptionPane.showMessageDialog(null, "Porfavor elija una unidad de medida distinta.");
            } else if (chbCEL2.isSelected()){
                double valorTemp = 0;
                double resp = 0;

                valorTemp = Double.parseDouble(   cajaTemp    );

                /*INTANCIO LA CLASE*/
                clsCalculoTemp objCalculoTemp = new clsCalculoTemp();

                resp = objCalculoTemp.fncFahrenheitAcelsius(valorTemp);

                JOptionPane.showMessageDialog(null, resp);
                ctRespTemp.setText(    String.valueOf(resp)    );
            } else if (chbKEL2.isSelected()){
                double valorTemp = 0;
                double resp = 0;

                valorTemp = Double.parseDouble(   cajaTemp    );

                /*INTANCIO LA CLASE*/
                clsCalculoTemp objCalculoTemp = new clsCalculoTemp();

                resp = objCalculoTemp.fncFahrenheitAkelvin(valorTemp);

                JOptionPane.showMessageDialog(null, resp);
                ctRespTemp.setText(    String.valueOf(resp)    );
            }
        } else if (chbKEL1.isSelected()){
            if (chbKEL2.isSelected()){
                JOptionPane.showMessageDialog(null, "Porfavor elija una unidad de medida distinta.");
            } else if (chbCEL2.isSelected()){
                double valorTemp = 0;
                double resp = 0;

                valorTemp = Double.parseDouble(   cajaTemp    );

                /*INTANCIO LA CLASE*/
                clsCalculoTemp objCalculoTemp = new clsCalculoTemp();

                resp = objCalculoTemp.fncKelvinAcelsius(valorTemp);

                JOptionPane.showMessageDialog(null, resp);
                ctRespTemp.setText(    String.valueOf(resp)    );
            } else if (chbFAH2.isSelected()){
                double valorTemp = 0;
                double resp = 0;

                valorTemp = Double.parseDouble(   cajaTemp    );

                /*INTANCIO LA CLASE*/
                clsCalculoTemp objCalculoTemp = new clsCalculoTemp();

                resp = objCalculoTemp.fncKelvinAfahrenheit(valorTemp);

                JOptionPane.showMessageDialog(null, resp);
                ctRespTemp.setText(    String.valueOf(resp)    );
            }
        }
    }//GEN-LAST:event_btnConverTempActionPerformed

    private void chbFAH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFAH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFAH1ActionPerformed

    private void chbFAH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFAH2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFAH2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ctRespTemp.setText("");
        ctTemp.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ctTempKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctTempKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') evt.consume();
        btnConverTemp.setEnabled(true);
    }//GEN-LAST:event_ctTempKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConverTemp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chbCEL1;
    private javax.swing.JCheckBox chbCEL2;
    private javax.swing.JCheckBox chbFAH1;
    private javax.swing.JCheckBox chbFAH2;
    private javax.swing.JCheckBox chbKEL1;
    private javax.swing.JCheckBox chbKEL2;
    private javax.swing.JTextField ctRespTemp;
    private javax.swing.JTextField ctTemp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
